# Generated by Django 5.0.1 on 2025-06-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(max_length=200),
        ),
    ]
