# Generated by Django 5.0.1 on 2025-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projects_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrollar_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Animation_imgs')),
            ],
        ),
    ]
