# Generated by Django 5.0.1 on 2025-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_scrollar_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollar_images',
            name='image',
            field=models.ImageField(upload_to='Scrollbar_imgs'),
        ),
    ]
